Update for 11-21-2019 03-45-15

diff --git a/run-mariabackup b/run-mariabackup
--- a/run-mariabackup
+++ b/run-mariabackup
@@ -43,6 +43,20 @@ function die() {
     exit "${2:-1}"
 }
 
+# This "auto-installs" the program into /usr/local/bin for ya!
+command -v "$PROGRAM_NAME" 1>/dev/null 2>&1 || {
+    (
+        if [ -x "${DIR}/${PROGRAM_NAME}" ]; then
+            sudo ln -svf "${DIR}/${PROGRAM_NAME}" "/usr/local/bin/${PROGRAM_NAME}"
+            sudo chmod -R 0775 "/usr/local/bin/${PROGRAM_NAME}"
+        else
+            echo "For some reason, linking ${PROGRAM_NAME} to /usr/local/bin,"
+            echo "failed. My apologies for not being able to figure it out..."
+            exit 1
+        fi
+    )
+}
+
 # This block tests for the existence of the needed configuration file
 if [ -f "/etc/${PROGRAM_NAME}.conf" ]; then
     . "/etc/${PROGRAM_NAME}.conf"
